### ISSUE TITLE
Cannot use API with node version 6 or below.

### ISSUE THREAD

**Issue by e-e-e** [beakerbrowser/pauls-dat-api#13]
I tried using your api in node 6.10, but  encountered errors caused by the es7 async functions. Do you have any plans to transpile this package in the prepublish step, so that it can be used in earlier versions of node that do not yet have native support for async/await?

I use babel in my own code for async/await but babel ignores node_modules.

**Comment by pfrazee** [comment]
Happy to add that, but I'll have to ask for a PR. (This lib is just something I use internally, I dont plan to provide active support atm.)

If you want to submit a PR, I'd ask that the transpile outputs a 'es5.js' at the toplevel, or some similar name. Then, a consumer of the transpiled form would use:

```js
require('pauls-dat-api/es5')
```

**Comment by e-e-e** [comment]
Excellent. Completely understandable. I will write up a pr over the next day or so.
Thanks for all your work - its been really useful for quickly starting a dat project with promises.

**Comment by pfrazee** [comment]
Solved with https://github.com/beakerbrowser/pauls-dat-api/pull/14. Thanks!
